import assert from 'node:assert/strict';
import { apply, balance, empty, forecast, plus, type State } from '../lib/runway';
const date='2026-09-07';let id=0;
const run=(s:State,c:Parameters<typeof apply>[1])=>apply(s,c,date,'event-'+(++id));
function base(){return run(empty(),{type:'budget',balance:310000,next:'2026-09-17',daily:25000,essentialDaily:12000,buffer:0,complete:true,consent:true});}
let s=base();
s=run(s,{type:'plan',title:'Kos',amount:140000,due:'2026-09-12',essential:true});
assert.equal(forecast(s,date)?.safe,17000);assert.equal(forecast(s,date)?.gap,80000);
const plan=s.plans[0].id;s=run(s,{type:'save',id:plan,amount:105000});
assert.equal(balance(s),310000);assert.equal(forecast(s,date)?.gap,45000);
s=run(s,{type:'pay',id:plan,amount:105000});assert.equal(balance(s),205000);assert.equal(forecast(s,date)?.mandatory,0);
assert.throws(()=>run(s,{type:'pay',id:plan,amount:105000}));
s=run(s,{type:'pending',title:'Honor survei',amount:40000,due:date});const income=s.incomes[0].id;
assert.equal(balance(s),205000);assert.equal(forecast(s,date)?.pending,40000);
s=run(s,{type:'receive',id:income,amount:40000});assert.equal(balance(s),245000);assert.throws(()=>run(s,{type:'receive',id:income,amount:40000}));
s=run(s,{type:'expense',title:'Cetak ulang',amount:20000});const expense=s.ledger.at(-1)!.id;
s=run(s,{type:'refund',id:expense,amount:5000});assert.equal(balance(s),230000);assert.throws(()=>run(s,{type:'refund',id:expense,amount:16000}));
const before=balance(s);s=run(s,{type:'transfer',title:'GoPay ke tunai',amount:50000});assert.equal(balance(s),before);
let optional=base();optional=run(optional,{type:'plan',title:'Kaos acara',amount:20000,due:'2026-09-09',essential:false});
optional=run(optional,{type:'defer',id:optional.plans[0].id,due:'2026-09-20'});assert.equal(forecast(optional,date)?.optional,0);assert.throws(()=>run(optional,{type:'defer',id:optional.plans[0].id,due:'2026-09-15'}));
let check=base();check=run(check,{type:'check',met:false,emergency:true});check=run(check,{type:'check',met:true,emergency:false});assert.equal(check.checks.length,1);assert.equal(check.checks[0].met,true);
assert.throws(()=>run(empty(),{type:'budget',balance:-1,next:'2026-09-17',daily:1,essentialDaily:1,buffer:0,complete:true,consent:true}));
assert.throws(()=>run(empty(),{type:'budget',balance:1,next:date,daily:1,essentialDaily:1,buffer:0,complete:true,consent:true}));
assert.equal(plus('2026-09-30',1),'2026-10-01');
console.log('15 aturan inti lolos.');
