'use client';
/* oxlint-disable next/no-html-link-for-pages -- SIWC and file downloads require top-level/plain anchors. */
import { useEffect, useRef, useState, type SyntheticEvent } from 'react';
import { Wallet, ArrowRight, ShieldCheck, Plus, ArrowUpRight, ArrowDownLeft, CalendarDays, Check, Info, RefreshCw, X, Leaf, Clock3, Download, Trash2, LayoutDashboard, ListChecks, Banknote, History, Settings2 } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Checkbox } from '@/components/ui/checkbox';
import { Tabs,TabsList,TabsTrigger,TabsContent } from '@/components/ui/tabs';
import { Dialog,DialogContent,DialogTitle,DialogDescription } from '@/components/ui/dialog';
import { AlertDialog,AlertDialogContent,AlertDialogTitle,AlertDialogDescription } from '@/components/ui/alert-dialog';
import { plus,type State,type Command,type forecast } from '@/lib/runway';
type Data={state:State;version:number;date:string;forecast:ReturnType<typeof forecast>};
type Modal={type:string;id?:string}|null;
const rp=(v:number)=>'Rp'+v.toLocaleString('id-ID');
const dt=(v:string)=>new Date(v+'T00:00:00Z').toLocaleDateString('id-ID',{day:'numeric',month:'short',timeZone:'UTC'});
const labels:Record<string,string>={budget:'Atur anggaran',plan:'Tambah kebutuhan',pay:'Catat pembayaran',save:'Pilih biaya lebih hemat',defer:'Tunda belanja opsional',daily:'Catat belanja harian',expense:'Catat biaya tambahan',income:'Catat uang masuk',pending:'Catat pemasukan menunggu',receive:'Konfirmasi uang diterima',refund:'Catat pengembalian dana',transfer:'Catat pindah uang sendiri',check:'Bagaimana kebutuhan hari ini?',formula:'Dari mana angkanya?'};
function Field({name,label,value,type='number',min=0,max=100000000,hint}:{name:string;label:string;value?:string|number;type?:string;min?:string|number;max?:string|number;hint?:string}){return <label className="field"><span>{label}</span><Input name={name} type={type} defaultValue={value} min={type==='text'?undefined:min} max={type==='text'?undefined:max} maxLength={type==='text'?100:undefined} step={type==='number'?1:undefined} required inputMode={type==='number'?'numeric':undefined}/>{hint&&<small>{hint}</small>}</label>;}
function Choice({name,children,checked=false}:{name:string;children:React.ReactNode;checked?:boolean}){return <label className="choice"><Checkbox name={name} defaultChecked={checked}/><span>{children}</span></label>;}
export default function RunwayApp(){
  const [data,setData]=useState<Data|null>(null),[tab,setTab]=useState('summary'),[modal,setModal]=useState<Modal>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState(''),[signIn,setSignIn]=useState(false),[loaded,setLoaded]=useState(false),[deleting,setDeleting]=useState(false);
  const pending=useRef<{serialized:string;requestId:string}|null>(null);
  const load=async()=>{setError('');try{const r=await fetch('/api/state',{cache:'no-store'});const d=await r.json() as Data&{error?:string};if(!r.ok){setSignIn(r.status===401);throw Error(d.error||'Catatan belum dapat dibuka.');}setData(d);setSignIn(false);pending.current=null;}catch(e){setError(e instanceof Error?e.message:'Koneksi terputus.');}finally{setLoaded(true);}};
  // Loading is the effect's external synchronization target.
  // oxlint-disable-next-line react/react-compiler
  useEffect(()=>{void load();},[]);
  const show=(type:string,id?:string)=>{setError('');setMessage('');setModal({type,id});};
  const mutate=async(command:Command)=>{
    if(!data||busy)return;setBusy(true);setError('');setMessage('');
    const serialized=JSON.stringify(command);
    if(!pending.current||pending.current.serialized!==serialized)pending.current={serialized,requestId:crypto.randomUUID()};
    try{const r=await fetch('/api/state',{method:'POST',headers:{'Content-Type':'application/json','X-Runway-Request':'1'},body:JSON.stringify({command,version:data.version,requestId:pending.current.requestId})});const d=await r.json() as Data&{error?:string};if(!r.ok){if(r.status===401)setSignIn(true);throw Error(d.error||'Belum berhasil menyimpan.');}setData(d);setModal(null);setDeleting(false);pending.current=null;setMessage(command.type==='delete'?'Catatan di aplikasi sudah dihapus.':'Tersimpan. Perkiraan sudah diperbarui.');}
    catch(e){setError(e instanceof Error?e.message:'Koneksi terputus. Muat ulang untuk memeriksa apakah catatan tersimpan.');}finally{setBusy(false);}
  };
  useEffect(()=>{
    const context=(document as Document&{modelContext?:{registerTool:(tool:unknown,options:unknown)=>Promise<void>|void}}).modelContext;
    if(!context)return;const lifecycle=new AbortController();
    try{void Promise.resolve(context.registerTool({name:'open_runway_entry_form',description:'Membuka formulir pencatatan untuk diperiksa pengguna. Tidak menyimpan atau mengubah saldo.',inputSchema:{type:'object',properties:{kind:{type:'string',enum:['daily','expense','income','plan','pending']}},required:['kind'],additionalProperties:false},annotations:{readOnlyHint:false},execute:(input:unknown)=>{const kind=(input as {kind?:string})?.kind;if(!kind||!['daily','expense','income','plan','pending'].includes(kind)||!data?.state.budget)throw Error('Jenis catatan tidak valid atau anggaran belum dibuat.');show(kind);return {opened:kind,saved:false};}},{signal:lifecycle.signal})).catch(()=>{});}catch{/* Browser yang belum mendukung tetap memakai formulir biasa. */}return()=>lifecycle.abort();
  },[data?.state.budget]);
  const s=data?.state,f=data?.forecast,b=s?.budget,date=data?.date;
  const plan=s?.plans.find(p=>p.id===modal?.id),income=s?.incomes.find(i=>i.id===modal?.id),entry=s?.ledger.find(e=>e.id===modal?.id);
  const submit=(event:SyntheticEvent<HTMLFormElement,SubmitEvent>)=>{event.preventDefault();const values=new FormData(event.currentTarget);const command:Command={type:modal!.type};if(modal?.id)command.id=modal.id;for(const [k,v]of values){const value=typeof v==='string'?v:'';command[k]=['balance','daily','essentialDaily','buffer','amount'].includes(k)?Number(value):value;}for(const k of ['complete','consent','essential','met','emergency'])if(['budget','plan','check'].includes(command.type))command[k]=values.has(k);void mutate(command);};
  const actions=(kind:string,label:string,Icon=Plus)=> <Button variant="outline" className="action-button" onClick={()=>show(kind)}><Icon size={18}/>{label}</Button>;
  return <main className="shell"><a className="skip" href="#content">Lewati navigasi</a><header className="top"><span className="brand">gopay <small>Campus Runway</small></span><div className="top-right"><span className="tag"><ShieldCheck size={16}/> Mode manual</span>{data&&<Button variant="ghost" aria-label="Muat ulang catatan" onClick={()=>void load()}><RefreshCw size={18}/></Button>}</div></header>
    {message&&<output className="notice success"><Check size={18}/>{message}</output>}
    {error&&!modal&&!deleting&&<div className="notice error" role="alert"><Info size={18}/><span>{error}</span>{!signIn&&<Button variant="outline" onClick={()=>void load()}>Muat ulang</Button>}</div>}
    {!b?<section id="content" className="welcome"><div><span className="eyebrow">RENCANA UANG SAKU</span><h1>Uang tenang.<br/>Kuliah jalan.</h1><p>Ketahui berapa yang bisa dipakai hari ini, sambil menjaga kebutuhan sampai uang saku berikutnya.</p>{!loaded?<output>Membuka catatanmu…</output>:signIn?<a className="link-primary" href="/signin-with-chatgpt?return_to=%2F" target="_top">Masuk untuk membuka catatan <ArrowRight size={18}/></a>:data?<Button className="primary" onClick={()=>show('budget')}>Atur uang sakumu <ArrowRight/></Button>:<Button onClick={()=>void load()}>Coba lagi</Button>}<p className="fine">Versi awal untuk uji terbatas. Bukan aplikasi resmi GoPay. Tidak melakukan transaksi uang.</p></div><aside className="hero-card"><Wallet/><p>Mulai dari yang kamu tahu</p><h2>Saldo tersedia.<br/>Kebutuhan penting.<br/>Tanggal uang saku.</h2><span>Tanpa menghubungkan rekening atau meminta PIN.</span></aside></section>:<>
    <div className="page-heading"><div><span className="eyebrow">{date&&dt(date)} · WAKTU JAKARTA</span><h1>Ruang untuk yang penting.</h1><p>Rencanamu sampai {dt(b.next)}. Satu langkah kecil, uang lebih terarah.</p></div><Button className="primary" onClick={()=>show('daily')}><Plus/> Catat belanja</Button></div>
    <Tabs value={tab} onValueChange={v=>setTab(String(v))}><TabsList className="main-tabs" aria-label="Bagian aplikasi"><TabsTrigger value="summary"><LayoutDashboard/>Ringkasan</TabsTrigger><TabsTrigger value="plans"><ListChecks/>Kebutuhan</TabsTrigger><TabsTrigger value="income"><Banknote/>Pemasukan</TabsTrigger><TabsTrigger value="activity"><History/>Aktivitas</TabsTrigger><TabsTrigger value="data"><Settings2/>Data</TabsTrigger></TabsList>
    <div id="content">
    <TabsContent value="summary">
      {f&&<>
      {(!f.complete||f.expired||f.unconfirmed)&&<div className="notice warning"><Info size={20}/><div><strong>{f.expired?'Jadwal uang saku sudah tiba.':!f.complete?'Data perlu dilengkapi.':'Periksa catatan hari ini.'}</strong><p>{f.expired?'Saldo tidak bertambah otomatis. Catat uang yang sudah diterima, lalu perbarui tanggal berikutnya.':!f.complete?'Perkiraan sementara: saldo atau biaya penting mungkin belum tercatat.':'Catat belanja yang terlewat sebelum memakai perkiraan ini, lalu isi cek harian.'}</p></div><Button variant="outline" onClick={()=>show(f.expired||!f.complete?'budget':'check')}>Perbarui</Button></div>}
      <div className="summary-grid"><section className="hero-card cash-card"><div className="card-top"><span><Wallet size={18}/> Bisa dipakai lagi hari ini</span><span className="small-tag">{f.expired?'Perlu jadwal baru':'Perkiraan'}</span></div><div className="big-money">{rp(f.safe)}</div><p>Setelah kebutuhan terjadwal, cadangan, dan biaya minimum hari berikutnya diperhitungkan.</p><div className="card-bottom"><span><CalendarDays size={18}/>{f.expired?'Perbarui jadwal':`${f.horizon} hari menuju ${dt(b.next)}`}</span><button onClick={()=>show('formula')}>Lihat hitungan <ArrowRight size={16}/></button></div></section>
      <section className={'outlook panel '+(f.gap?'caution':'calm')}><span className="eyebrow">MENURUT RENCANA SAAT INI</span><h2>{f.expired?'Periode perlu diperbarui':f.critical?'Kebutuhan utama belum tertutup':f.gap?'Masih ada selisih':f.complete?'Diperkirakan cukup':'Perkiraan sementara'}</h2><div className="medium-money">{f.expired?'—':f.gap?rp(f.gap):rp(f.remainder)}</div><p>{f.expired?'Jangan memakai proyeksi lama sebagai patokan periode baru.':f.gap?'Perkiraan kekurangan sampai uang saku berikutnya.':'Perkiraan sisa akhir sebelum target cadangan.'}</p>{f.reserveGap>0&&!f.expired&&<p>Target cadangan masih kurang {rp(f.reserveGap)}.</p>}<Button variant="outline" onClick={()=>setTab('plans')}>Tinjau kebutuhan <ArrowRight/></Button></section></div>
      <div className="stats"><div><span>Saldo tercatat</span><strong>{rp(f.cash)}</strong><small>Bukan saldo yang ditarik dari rekening</small></div><div><span>Kebutuhan wajib tersisa</span><strong>{rp(f.mandatory)}</strong><small>Alokasi rencana, bukan uang terkunci</small></div><div><span>Belanja harian hari ini</span><strong>{rp(f.spentToday)}</strong><small>Sudah mengurangi saldo dan jatah hari ini</small></div></div>
      <div className="section-grid"><section className="panel"><div className="section-title"><h2>Yang mendekat</h2><button onClick={()=>setTab('plans')}>Lihat semua <ArrowUpRight size={16}/></button></div>{s!.plans.filter(p=>!p.paid).sort((a,c)=>a.due.localeCompare(c.due)).slice(0,3).map(p=><div className="upcoming" key={p.id}><div className="date-box">{dt(p.due)}</div><div><strong>{p.title}</strong><p>{p.essential?'Kebutuhan wajib':'Belanja opsional'}</p></div><b>{rp(p.amount)}</b></div>)}{!s!.plans.some(p=>!p.paid)&&<div className="empty-state"><ListChecks/><p>Belum ada kebutuhan terjadwal. Catat tagihan atau keperluan kelas agar uangnya ikut diperhitungkan.</p><Button variant="outline" onClick={()=>show('plan')}>Tambah kebutuhan</Button></div>}</section>
      <section className="panel check-card"><span className="icon-square"><Check/></span><h2>Kebutuhanmu terpenuhi?</h2><p>Cek singkat membantu membedakan rencana yang terlihat baik dengan keadaan sehari-hari.</p><Button variant="outline" onClick={()=>show('check')}>{s!.checks.some(c=>c.date===date)?'Perbarui cek hari ini':'Isi cek hari ini'}</Button></section></div>
      {!f.expired&&<details className="panel"><summary>Lihat perkiraan saldo harian <span className="fine">Jadwal kebutuhan + rata-rata belanja</span></summary><p>Uang yang belum diterima tidak dihitung. Tanggal risiko mengikuti rencana, bukan jaminan saldo rekening.</p><div className="timeline">{f.points.map(p=><div key={p.date}><span>{dt(p.date)}</span><strong className={p.balance<0?'negative':''}>{p.balance<0?'Kurang '+rp(-p.balance):rp(p.balance)}</strong></div>)}</div></details>}
      </>}
    </TabsContent>
    <TabsContent value="plans"><div className="section-title"><div><h2>Kebutuhan, bukan sekadar daftar.</h2><p>Biaya di sini terpisah dari belanja harian. Jangan masukkan kebutuhan yang sama dua kali.</p></div>{actions('plan','Tambah kebutuhan')}</div><div className="plan-grid">{s!.plans.map(p=><article className="panel plan-card" key={p.id}><div className="card-top"><span className={'tag '+(p.essential?'essential':'')}>{p.paid?'Sudah dibayar':p.essential?'Wajib':'Opsional'}</span><span className="fine">{dt(p.due)}</span></div><h2>{p.title}</h2><strong className="plan-money">{rp(p.amount)}</strong>{p.original>p.amount&&<p className="saving"><Leaf size={16}/> Rencana lebih hemat {rp(p.original-p.amount)}</p>}{p.deferredFrom&&<p>Dipindah dari {dt(p.deferredFrom)}; kebutuhan tetap tercatat.</p>}{!p.paid&&<div className="plan-actions"><Button className="primary" onClick={()=>show('pay',p.id)}>Sudah dibayar</Button><Button variant="outline" onClick={()=>show('save',p.id)}>Hemat</Button>{!p.essential&&<Button variant="outline" onClick={()=>show('defer',p.id)}>Tunda</Button>}{p.original>p.amount&&<Button variant="ghost" disabled={busy} onClick={()=>void mutate({type:'undoSave',id:p.id})}>Batalkan hemat</Button>}{p.deferredFrom&&<Button variant="ghost" disabled={busy} onClick={()=>void mutate({type:'undoDefer',id:p.id})}>Batalkan tunda</Button>}</div>}</article>)}</div>{!s!.plans.length&&<div className="empty-state panel"><ListChecks/><h2>Mulai dari kebutuhan terdekat.</h2><p>Misalnya tagihan kos atau pembelian buku. Nominal dan tanggalnya bisa kamu tentukan sendiri.</p></div>}<div className="notice"><Info/><p>Hemat mengubah biaya rencana, bukan menambah saldo. Tunda hanya untuk kebutuhan opsional. Pembayaran menutup rencana dan mengurangi saldo satu kali.</p></div></TabsContent>
    <TabsContent value="income"><div className="section-title"><div><h2>Uang masuk, statusnya jelas.</h2><p>Menunggu bukan berarti sudah bisa dibelanjakan.</p></div><div className="button-row">{actions('pending','Masih menunggu',Clock3)}{actions('income','Sudah diterima',ArrowDownLeft)}</div></div><div className="stats two"><div><span>Masih menunggu</span><strong>{rp(f?.pending??0)}</strong><small>Tidak menambah saldo atau perkiraan akhir</small></div><div><span>Konfirmasi berdasarkan uang diterima</span><p>Catat nominal bersih yang benar-benar masuk, bukan nilai yang dijanjikan.</p></div></div>{s!.incomes.map(i=><article className="panel income-row" key={i.id}><span className="icon-square"><Banknote/></span><div><h3>{i.title}</h3><p>{dt(i.due)} · {i.status==='received'?'Penerimaan tercatat':'Menunggu penerimaan'}</p></div><strong>{rp(i.amount)}</strong>{i.status==='waiting'&&<Button className="primary" onClick={()=>show('receive',i.id)}>Konfirmasi diterima</Button>}</article>)}<section className="panel empty-state"><ShieldCheck/><h2>Belum ada peluang partner terverifikasi.</h2><p>Kami belum menampilkan lowongan. Jika kamu sudah punya pekerjaan atau honor yang disepakati, catat sendiri sebagai pemasukan menunggu.</p></section></TabsContent>
    <TabsContent value="activity"><div className="section-title"><div><h2>Setiap perubahan ada catatannya.</h2><p>Nominal dicatat hari ini, dengan waktu Jakarta.</p></div></div><div className="button-row activity-buttons">{actions('daily','Belanja harian')}{actions('expense','Biaya tambahan')}{actions('income','Uang masuk')}{actions('transfer','Pindah uang sendiri')}</div><section className="panel ledger">{[...s!.ledger].reverse().map(e=><div className="ledger-row" key={e.id}><span className={'icon-square '+(['income','refund'].includes(e.kind)?'credit':'')}>{['income','refund'].includes(e.kind)?<ArrowDownLeft/>:<ArrowUpRight/>}</span><div><strong>{e.note}</strong><p>{dt(e.date)} · {{daily:'Belanja harian',expense:'Tambahan di luar rencana',payment:'Pembayaran kebutuhan',income:'Uang diterima',refund:'Pengembalian',transfer:'Pindah antar-akun sendiri'}[e.kind]}</p></div><b>{e.kind==='transfer'?'Tidak mengubah saldo':(['income','refund'].includes(e.kind)?'+':'−')+rp(e.amount)}</b>{['daily','expense','payment'].includes(e.kind)&&<Button variant="ghost" onClick={()=>show('refund',e.id)}>Refund</Button>}</div>)}{!s!.ledger.length&&<div className="empty-state"><History/><h2>Belum ada perubahan uang.</h2><p>Rencana tersimpan di Kebutuhan. Aktivitas ini mencatat uang yang benar-benar keluar atau masuk.</p></div>}</section><p className="fine">Pembayaran kebutuhan dicatat dari kartu kebutuhan. Refund tidak otomatis membuka kembali kewajiban; tambahkan kebutuhan baru jika pembelian masih harus dilakukan.</p></TabsContent>
    <TabsContent value="data"><div className="section-grid"><section className="panel"><span className="eyebrow">ANGGARAN & KELENGKAPAN</span><h2>Sesuaikan dengan keadaanmu.</h2><dl><div><dt>Uang saku berikutnya</dt><dd>{dt(b.next)}</dd></div><div><dt>Rencana belanja harian</dt><dd>{rp(b.daily)}</dd></div><div><dt>Minimum kebutuhan harian</dt><dd>{rp(b.essentialDaily)}</dd></div><div><dt>Target cadangan</dt><dd>{rp(b.buffer)}</dd></div><div><dt>Data lengkap</dt><dd>{b.complete?'Sudah dikonfirmasi':'Belum lengkap'}</dd></div></dl><Button variant="outline" onClick={()=>show('budget')}>Ubah anggaran</Button><p className="fine">Mengubah anggaran mempertahankan riwayat. Saldo berubah melalui catatan uang masuk/keluar, bukan ditimpa.</p></section><section className="panel"><span className="eyebrow">KENDALI DATA</span><h2>Catatanmu tetap milikmu.</h2><p>Data anggaran, kebutuhan, dan aktivitas disimpan untuk akunmu. Tidak ada akses PIN, OTP, atau rekening.</p><div className="button-row"><a className="link-outline" href="/api/export" download><Download size={18}/>Ekspor data</a><Button variant="outline" className="danger" onClick={()=>{setError('');setDeleting(true);}}><Trash2/>Hapus catatan</Button></div><p className="fine">Hapus akan mengosongkan data aktif dan persetujuan di aplikasi. Salinan ekspor yang kamu unduh tetap ada di perangkatmu. Penghapusan backup mengikuti kebijakan penyedia hosting dan perlu ditetapkan sebelum pilot peserta.</p><a className="text-link" href="/signout-with-chatgpt?return_to=%2F" target="_top">Keluar dari sesi</a></section></div><section className="panel"><h2>Catatan manfaat, bukan janji hasil.</h2><div className="stats two"><div><span>Hari yang sudah dicek</span><strong>{s!.checks.length}</strong></div><div><span>Hari kebutuhan belum terpenuhi</span><strong>{s!.checks.filter(c=>!c.met).length}</strong></div></div><p>{s!.checks.filter(c=>c.emergency).length} hari melibatkan bantuan atau pinjaman darurat. Ini laporan mandiri, belum membuktikan dampak produk.</p></section></TabsContent>
    </div></Tabs><footer>Versi awal · Pencatatan manual · Bukan layanan resmi GoPay · Tidak melakukan pembayaran atau menawarkan kredit</footer></>}
    <Dialog open={!!modal} onOpenChange={v=>{if(!v&&!busy){setModal(null);setError('');}}}><DialogContent className="runway-dialog" showCloseButton={false}><div className="dialog-heading"><DialogTitle>{labels[modal?.type??'']??'Catatan'}</DialogTitle><Button variant="ghost" aria-label="Tutup dialog" disabled={busy} onClick={()=>{setModal(null);setError('');}}><X/></Button></div><DialogDescription>{modal?.type==='budget'?'Saldo tidak termasuk limit kredit atau uang milik orang lain.':modal?.type==='formula'?'Perkiraan mengikuti data yang kamu catat, bukan akses ke rekening.':'Periksa nominal dan keterangannya sebelum disimpan. Ini pencatatan, bukan transaksi uang.'}</DialogDescription>
    {modal?.type==='formula'&&f&&b?<div className="formula"><dl><div><dt>Saldo tersedia</dt><dd>{rp(f.cash)}</dd></div><div><dt>Kebutuhan wajib + opsional terjadwal</dt><dd>{rp(f.mandatory+f.optional)}</dd></div><div><dt>Cadangan</dt><dd>{rp(b.buffer)}</dd></div><div><dt>Belanja harian sudah dibayar hari ini</dt><dd>{rp(f.spentToday)}</dd></div><div><dt>Hari tersisa</dt><dd>{f.horizon}</dd></div></dl><p>Jatah total hari ini = (saldo + belanja harian hari ini − kebutuhan terjadwal − cadangan) dibagi hari tersisa, dibulatkan ke bawah. Kurangi belanja harian yang sudah dibayar.</p><p>Hasil juga dibatasi agar minimum kebutuhan hari berikutnya tetap tersedia. Tidak boleh negatif. Penghasilan menunggu tidak dihitung.</p><p>Biaya terjadwal berdiri sendiri, di luar rata-rata harian. Perkiraan akhir mengurangi rencana harian yang belum dibayar dan semua kebutuhan terjadwal periode ini.</p></div>:<form key={modal?.type+':'+(modal?.id??'')} onSubmit={submit} onInvalidCapture={e=>{const t=e.target as HTMLInputElement;t.setCustomValidity(t.validity.valueMissing?'Bagian ini perlu diisi.':'Periksa nilai dan batas yang tertera.');setError('Ada isian yang perlu diperbaiki.');}} onInput={e=>(e.target as HTMLInputElement).setCustomValidity?.('')}>
      {modal?.type==='budget'&&<><div className="form-grid">{!b&&<Field name="balance" label="Saldo tersedia (Rp)" hint="Gabungkan uang tunai dan saldo yang boleh dipakai."/>}<Field name="next" label="Uang saku berikutnya" type="date" value={b?.next??(date?plus(date,30):'')} min={date?plus(date,1):undefined} max={date?plus(date,90):undefined}/><Field name="daily" label="Rencana belanja harian (Rp)" value={b?.daily} hint="Di luar biaya yang kamu masukkan sebagai kebutuhan terjadwal."/><Field name="essentialDaily" label="Minimum kebutuhan harian (Rp)" value={b?.essentialDaily} hint="Bagian dari belanja harian untuk makan/perjalanan wajib; bukan tambahan biaya."/><Field name="buffer" label="Cadangan tambahan (Rp)" value={b?.buffer??0}/></div><Choice name="complete" checked={b?.complete}>Saldo dan semua biaya penting sudah tercatat. Saya akan menambahkan kebutuhan terjadwal setelah ini.</Choice><Choice name="consent" checked={!!s?.consent}>Saya setuju data catatan disimpan untuk perencanaan akun ini. Saya bisa mengekspor dan menghapusnya di menu Data.</Choice><p className="fine">Versi uji terbatas: gunakan angka contoh dulu. Retensi dan dukungan pilot peserta belum diaktifkan.</p></>}
      {modal?.type==='plan'&&<><Field name="title" label="Kebutuhan apa?" type="text"/><div className="form-grid"><Field name="amount" label="Biaya rencana (Rp)" min={1}/><Field name="due" label="Perlu dibayar tanggal" type="date" min={date} max={date?plus(date,180):undefined} value={date}/></div><Choice name="essential" checked>Kebutuhan wajib, tidak boleh ditunda.</Choice><p className="fine">Jangan masukkan biaya yang sudah termasuk rata-rata harian. Biaya ini ditambahkan di luar rata-rata itu.</p></>}
      {['pay','save','receive','refund'].includes(modal?.type??'')&&<><p className="selected-record">{plan?.title??income?.title??entry?.note}</p><Field name="amount" label={modal?.type==='save'?'Total biaya alternatif (Rp)':modal?.type==='refund'?'Dana yang dikembalikan (Rp)':'Nominal benar-benar dibayar / diterima (Rp)'} value={modal?.type==='refund'?undefined:plan?.amount??income?.amount} min={1}/>{modal?.type==='save'&&<p className="fine">Masukkan total termasuk ongkos tambahan. Pastikan kebutuhan tetap terpenuhi. Saldo belum berubah sampai pembayaran dicatat.</p>}{modal?.type==='pay'&&<p className="fine">Menandai kebutuhan ini lunas seluruhnya. Nominal aktual boleh berbeda dari rencana. Untuk pembayaran sebagian, gunakan kebutuhan terpisah terlebih dahulu.</p>}{modal?.type==='refund'&&<p className="fine">Refund tidak menghapus catatan asal dan tidak otomatis membuka kembali kebutuhan. Ini bukan pemasukan baru dari pekerjaan.</p>}</>}
      {modal?.type==='defer'&&<><p>{plan?.title} · {rp(plan?.amount??0)}</p><Field name="due" label="Tanggal baru" type="date" min={b?.next} max={date?plus(date,180):undefined} value={b?.next}/><p>Kebutuhan tetap tercatat pada tanggal baru. Menunda tidak berarti hemat permanen.</p></>}
      {['daily','expense','income','transfer','pending'].includes(modal?.type??'')&&<><Field name="title" label="Keterangan" type="text"/><Field name="amount" label="Nominal (Rp)" min={1}/>{modal?.type==='pending'&&<Field name="due" label="Perkiraan diterima" type="date" min={date} max={date?plus(date,180):undefined} value={date}/>}<p className="fine">{modal?.type==='daily'?'Untuk belanja dalam rata-rata harian. Mengurangi saldo dan bagian rencana hari ini.':modal?.type==='expense'?'Hanya biaya tambahan di luar rencana harian maupun kebutuhan terjadwal.':modal?.type==='transfer'?'Hanya antar-akun milikmu yang keduanya sudah masuk saldo gabungan. Saldo gabungan tidak berubah. Biaya transfer dicatat terpisah.':modal?.type==='pending'?'Gunakan pekerjaan atau honor yang sudah kamu ketahui. Tidak menambah saldo sampai kamu konfirmasi diterima.':'Catat hanya uang yang sudah masuk. Jika berasal dari daftar menunggu, gunakan tombol Konfirmasi diterima pada catatan itu.'}</p></>}
      {modal?.type==='check'&&<><Choice name="met" checked={s?.checks.find(c=>c.date===date)?.met??true}>Kebutuhan penting hari ini terpenuhi.</Choice><Choice name="emergency" checked={s?.checks.find(c=>c.date===date)?.emergency}>Ada bantuan tambahan atau pinjaman darurat hari ini.</Choice><p>Pastikan semua belanja dan perubahan saldo hari ini sudah dicatat. Jawaban ini disimpan per hari, bukan digandakan saat diperbarui.</p></>}
      {error&&<div className="notice error" role="alert">{error}<Button type="button" variant="ghost" onClick={()=>void load()}>Muat ulang data</Button></div>}<div className="form-footer"><Button type="button" variant="outline" disabled={busy} onClick={()=>{setModal(null);setError('');}}>Batal</Button><Button type="submit" className="primary" disabled={busy}>{busy?'Menyimpan…':'Simpan catatan'}<Check size={18}/></Button></div></form>}
    </DialogContent></Dialog>
    <AlertDialog open={deleting} onOpenChange={v=>{if(!busy)setDeleting(v);}}><AlertDialogContent><AlertDialogTitle>Hapus seluruh catatan?</AlertDialogTitle><AlertDialogDescription>Anggaran, kebutuhan, aktivitas, cek harian, dan persetujuan aktif akan dihapus dari aplikasi. Ekspor dulu jika ingin menyimpan salinan. Tindakan ini tidak dapat dibatalkan.</AlertDialogDescription>{error&&<p role="alert" className="negative">{error}</p>}<div className="button-row"><Button variant="outline" disabled={busy} onClick={()=>setDeleting(false)}>Batal</Button><Button className="danger" disabled={busy} onClick={()=>void mutate({type:'delete'})}>{busy?'Menghapus…':'Hapus semua catatan'}</Button></div></AlertDialogContent></AlertDialog>
  </main>;
}
